export
const medicines = [
    {
      id: 1,
      name: "Paracetamol 500mg",
      price: 2.99,
      description: "Effective pain reliever and fever reducer. Suitable for headaches, colds, and flu symptoms.",
      image: "",
      manufacturer: "GlaxoSmithKline",
      availability: "In Stock",
    },
    {
      id: 2,
      name: "Ibuprofen 400mg",
      price: 4.50,
      description: "Nonsteroidal anti-inflammatory drug (NSAID) for reducing inflammation, pain, and fever.",
      image: "",
      manufacturer: "Pfizer",
      availability: "Limited Stock",
    },
    {
      id: 3,
      name: "Amoxicillin 250mg",
      price: 7.99,
      description: "Broad-spectrum antibiotic used to treat various bacterial infections.",
      image: "",
      manufacturer: "Abbott Laboratories",
      availability: "In Stock",
    },
    {
      id: 4,
      name: "Cetirizine 10mg",
      price: 3.25,
      description: "Antihistamine for relief from allergies, hay fever, and hives.",
      image: "",
      manufacturer: "Zydus Cadila",
      availability: "In Stock",
    },
    {
      id: 5,
      name: "Metformin 500mg",
      price: 5.99,
      description: "Medication for managing type 2 diabetes by controlling blood sugar levels.",
      image: "",
      manufacturer: "Sun Pharma",
      availability: "Out of Stock",
    },
    {
      id: 6,
      name: "Azithromycin 500mg",
      price: 9.50,
      description: "",
      image: "https://images.unsplash.com/photo-1580910051071-94bc9ba060aa?auto=format&fit=crop&w=400&q=60",
      manufacturer: "Cipla",
      availability: "In Stock",
    },
    {
      id: 7,
      name: "Loratadine 10mg",
      price: 2.75,
      description: "Non-drowsy antihistamine for allergies, sneezing, and itchy eyes.",
      image: "",
      manufacturer: "Bayer",
      availability: "In Stock",
    },
    {
      id: 8,
      name: "Omeprazole 20mg",
      price: 6.40,
      description: "Proton pump inhibitor for treating acid reflux, heartburn, and stomach ulcers.",
      image: "",
      manufacturer: "Dr. Reddy's Laboratories",
      availability: "Limited Stock",
    },
    {
      id: 9,
      name: "Vitamin D3 1000 IU",
      price: 3.99,
      description: "Dietary supplement supporting bone health and immune system.",
      image: "",
      manufacturer: "Nature's Bounty",
      availability: "In Stock",
    },
    {
      id: 10,
      name: "Aspirin 81mg",
      price: 2.50,
      description: "Low-dose aspirin for heart health and blood thinning.",
      image: "",
      manufacturer: "Johnson & Johnson",
      availability: "In Stock",
    }
  ];
  